### ISSUE TITLE
Your requested instance type (a1.large) is not supported in your requested Availability Zone

### ISSUE THREAD

**Issue by grisu48** [SUSE-Enceladus/ec2imgutils#103]
When using `ec2uploadimg` for uploading arm64 images to the `us-east-1` region, there is a chance that the call will fail because an Availability zone without ARM instances will be picked for the VM (e.g. `us-east-1f`).

The issue arises only sometimes when using certain regions. We're using the `us-east-1` region for arm64 testing, and the call sometimes fails, and sometimes it passes (likely depending on the internal choice of the availability zone).

Example:

```
ec2uploadimg --access-id <redacted> -s <redacted> --backing-store ssd --grub2 --machine 'arm64' -n 'openqa-SLES15-SP4-Micro-5-3-BYOS.aarch64-1.0.2-EC2-Build1.3.raw.xz' --virt-type hvm --sriov-support --ena-support --verbose --regions 'us-east-1' --ssh-key-pair <redacted> --private-key-file <redacted> -d 'OpenQA upload image' --wait-count 3 --ec2-ami <redacted> --type 'a1.large' --user 'ec2-user' 'SLES15-SP4-Micro-5-3-BYOS.aarch64-1.0.2-EC2-Build1.3.raw.xz'
...
Successfully allowed incoming SSH port 22 for security group sg-<redaced> in vpc-<redacted>

An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (a1.large) is not supported in your requested Availability Zone (us-east-1f). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1d.
Traceback (most recent call last):
  File "/root/.venv_ec2uploadimg/bin/ec2uploadimg", line 957, in upload_image_to_region
    ami = uploader.create_image(args.source)
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/ec2imgutils/ec2uploadimg.py", line 1022, in create_image
    snapshot = self.create_snapshot(source)
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/ec2imgutils/ec2uploadimg.py", line 1161, in create_snapshot
    root_volume = self._create_image_root_volume(source)
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/ec2imgutils/ec2uploadimg.py", line 354, in _create_image_root_volume
    helper_instance = self._launch_helper_instance()
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/ec2imgutils/ec2uploadimg.py", line 764, in _launch_helper_instance
    instance = self._connect().run_instances(
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.venv_ec2uploadimg/lib64/python3.10/site-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (a1.large) is not supported in your requested Availability Zone (us-east-1f). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1d.
An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (a1.large) is not supported in your requested Availability Zone (us-east-1f). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1d.
Successfully deleted security group sg-<redacted>
```
See https://openqa.suse.de/tests/11897135#step/upload_image/86

**Comment by grisu48** [comment]
Note: Due to limitations with other necessary features of the AWS CLI we can't specify a specific availability zone e.g. `us-east-1a`. The AWS CLI does not allow that.

**Comment by smarlowucf** [comment]
This is not an ec2imgutils issue. I suspect you are using a marketplace image. These images each have a list of supported instance types. It's likely the image you are using does not support a1. Suggest finding a different arm64 type from https://aws.amazon.com/ec2/graviton/.

**Comment by smarlowucf** [comment]
Closing

**Comment by smarlowucf** [comment]
This is not an ec2imgutils issue. I suspect you are using a marketplace image. These images each have a list of supported instance types. It's likely the image you are using does not support a1. Suggest finding a different arm64 type from https://aws.amazon.com/ec2/graviton/.

**Comment by rjschwei** [comment]
You do not need to use an aarch64 instance to upload an aarch64 image. Also you can use an instance type m6g if you do want to use an aarch64 image that is more readily available. Last but not least placement, i.e. availability zone is associated with the subnet. And you can set the subnet and the help instance type in the config file or on the command line.

**Comment by grisu48** [comment]
We're using this to upload an image, we're not using a marketplace image.

@rjschwei I'm not sure this is true - We tried to use `t2.large` type in `ec2uploadimg`, and this didn't work:

```
ec2uploadimg <snip> --machine 'arm64' --type 't2.large' <snip>
...
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
An error occurred (InvalidParameterValue) when calling the RunInstances operation: The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
```

However, I follow Sean's recommendation and use `m7g` or `t4g`. Will report back later today.

**Comment by rjschwei** [comment]
@grisu48 yes it works I do it all the time. I bet on your command line you are using the `-e` or `--ec2-ami` to set the ami-id for the helper image and the ami-id you are specifying is an aarch64 ami. That will of course not work. This is alos what the error message is telling you

```
when calling the RunInstances operation: The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI.
```
so if you us the ami id of an x86_64 image instead of an aarch64 image it will work just fine.

**Comment by grisu48** [comment]
> @grisu48 yes it works I do it all the time. I bet on your command line you are using the `-e` or `--ec2-ami` to set the ami-id for the helper image and the ami-id you are specifying is an aarch64 ami. That will of course not work. This is alos what the error message is telling you
> 
> ```
> when calling the RunInstances operation: The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI.
> ```
> 
> so if you us the ami id of an x86_64 image instead of an aarch64 image it will work just fine.

Yes, you are right, this is indeed pointing to an x86_64 image! Thanks, now I understand where this is coming from.

**Comment by smarlowucf** [comment]
Thanks for more details @rjschwei 👍🏼

**Comment by grisu48** [comment]
Switching to `m6g.medium` seems to do the job. I've not observed any more failures since.

Thanks Sean and Robert! :+1:
