### ISSUE TITLE
Create image from existing snapshot

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/ec2imgutils#23]
ec2uploadimg should have an option to create an image from and exiting snapshot. this should support root-swap as well as "regular" image registration.

**Comment by rjschwei** [comment]
@davdunc issue recorded

**Comment by KeithMnemonic** [comment]
Robert, the current set of options has a "snapOnly" . I am guessing that is not a valid option if we use an existing snapshot. Can  you confirm the expected bahavior? I think this is an XOR operation but want to be sure of the use case.

**Comment by rjschwei** [comment]
`ec2uploadimg --use-snapshot snap-123` is also XOR with `--use-root-swap` and others. Basically the command line arguments accepted that do not directly relate to the `register-image` API are superfluous for the `--use-snapshot` option.

This is a shortcut when the user uploaded an image and then realizes they made a typo in the name of the image. The only way to correct that today is to do a full re-upload.
