### ISSUE TITLE
support use of aws cli config file

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/ec2imgutils#26]
If the access and secret keys are missing in the ec2utils config file the config file for the aws cli should be used to try and find the keys.

**Comment by KeithMnemonic** [comment]
Robert, a few questions avout the expected behavior.

1) Would you expect it to fall back to the aws creds only if the file was missing the keys or also if the file does not even exist.  To be more exact, should the cli just use the aws creds if the ec2utils.conf file is not present. Currenty the tool exits when the file is not present.   There are two checks that may need to be done to determine when to use AWS creds. 

2)  Would you expect it to look for the "default" aws profile for the keys by default,  but also have an option to use a speficic profile?

**Comment by rjschwei** [comment]
Yes if `access_key_id` and `secret_access_key` are missing in ec2utils.conf and not specified on the command line we want to read from `.aws/config`. The entry `profile` entry in `.aws/config` will have to match what is specified a `--account` on the command line, meaning `[profile default]` is ignored by ec2imgutils. Otherwise we have to do too much guess work.

**Comment by KeithMnemonic** [comment]
Ok so if ec2utils.conf does not exist , we just exit normally as we do now?

**Comment by rjschwei** [comment]
> Ok so if ec2utils.conf does not exist , we just exit normally as we do now?

Before exit we look for `.aws/config` see if we can find a matching `[profile]` entry for the specified account and if we can we proceed and if not we bitch that we cannot find the account in either `.ec2utils.conf` nor in `.aws/config`

**Comment by KeithMnemonic** [comment]
Robert, As I dig into this , the default aws credential files seems to be more organized to the region in .ec2utils.conf as opposed to the account. Would it be acceptable to pull from the region value?

**Comment by KeithMnemonic** [comment]
> Robert, As I dig into this , the default aws credential files seems to be more organized to the region in .ec2utils.conf as opposed to the account. Would it be acceptable to pull from the region value?

I figured out how to do it.

**Comment by KeithMnemonic** [comment]
Robert,

So I have something like this working, will it work for you?

(ec2imgutils) kberger@opensuse:~/venv/ec2imgutils> ./bin/ec2listimg -a east-1  -r us-east-2
Unable to get access_key_id value from account east-1, Trying the aws credentials file.
Unable to get secret_access_key value from account east-1, Trying the aws credentials file.
kberger_sle15_test1
openSUSE-Leap-15.1-v20200514-hvm-ssd-x86_64
openSUSE-Leap-15.1-v20200612-hvm-ssd-x86_64
kberger_sle15_test
openSUSE-Leap-15.1-v20200518-hvm-ssd-x86_64
openSUSE-Leap-15.1-v20200611-hvm-ssd-x86_64
openSUSE-Leap-15.1-v20200607-hvm-ssd-x86_64

**Comment by rjschwei** [comment]
So .aws/config is not as rich as .ec2utils.conf for obvious reasons as the additional data in .ec2utils.conf is simply not needed to operate the AWS CLI tools. But at present one has to for example store access key and secret access key in 2 files, .aws/config for the aws cli and in .ec2utils.conf to use ec2imgutils. The idea is to reduce the duplication. Meaning I can setup a .aws/config with

```
[profile foo]
aws_access_key_id = 1234
aws_secret_access_key = 5678
```

and I can have .ec2utils.conf with

```
[account-foo]
ssh_key_name = ....
ssh_private_key = .....
```

and now `ec2uploadimg -a foo ....` would still work because the code can pick up the keys from the .aws/config file

**Comment by rjschwei** [comment]
> Robert,
> 
> So I have something like this working, will it work for you?
> 
> (ec2imgutils) kberger@opensuse:~/venv/ec2imgutils> ./bin/ec2listimg -a east-1 -r us-east-2
> Unable to get access_key_id value from account east-1, Trying the aws credentials file.
> Unable to get secret_access_key value from account east-1, Trying the aws credentials file.
> kberger_sle15_test1
> openSUSE-Leap-15.1-v20200514-hvm-ssd-x86_64
> openSUSE-Leap-15.1-v20200612-hvm-ssd-x86_64
> kberger_sle15_test
> openSUSE-Leap-15.1-v20200518-hvm-ssd-x86_64
> openSUSE-Leap-15.1-v20200611-hvm-ssd-x86_64
> openSUSE-Leap-15.1-v20200607-hvm-ssd-x86_64

Without the messages, as user I really do not care where the code picks up the necessary access keys to perform it's operations.
