### ISSUE TITLE
verify - ec2publishimg --share-with none appears to throw when the image is not shared already

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/ec2imgutils#32]

**Comment by KeithMnemonic** [comment]
Can you provide more details of how/where you saw this? I have an AMI that is currently listed as private. 

kberger_sle15_test | ami-092b9f9f8ab6e50c9 | 810320120389/kberger_sle15_test | 810320120389 | Private

ec2publishimg -a AWS-RD --image-id ami-092b9f9f8ab6e50c9 -r us-east-2 --share-with none
        Image with ID: ami-092b9f9f8ab6e50c9  is already private, nothing to do

Was this how you tested/saw this?

**Comment by rjschwei** [comment]
Thanks for testing, yes that would be th etest.
