### ISSUE TITLE
support for EC2 instance type t3

### ISSUE THREAD

**Issue by sveldhuisen** [SUSE-Enceladus/ec2imgutils#35]
Hello,

I'm not sure whether EC2 instance type t3 is supported, but it is currently not  working with ec2uploadimg. I get the following error when uploading a raw image:

`Could not find disk device in helper instance with path /dev/sdf`

When I deploy my raw image to an instance type t2 it dsoes work. Due certain load patterns I would prefer instance type t3.

**Comment by rjschwei** [comment]
Yes instance types that attach disks via NVMe protocol do not work ATM, fixed in #34

**Comment by sveldhuisen** [comment]
Hi Robert,

thanks for the confirmation and the fix.
