### ISSUE TITLE
ec2publishimg should wait for image avialability

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/ec2imgutils#45]
When the image is pending it cannot be published. ec2publishimg generates a traceback

An error occurred (InvalidAMIID.Unavailable) when calling the ModifyImageAttribute operation: The AMI ID 'ami-0aef1f7c38d24d19c' is currently pending and may not be used for this operation
Traceback (most recent call last):
  File "/usr/bin/ec2publishimg", line 254, in <module>
    publisher.publish_images()
  File "/usr/lib/python3.6/site-packages/ec2imgutils/ec2publishimg.py", line 207, in publish_images
    UserIds=self.visibility.split(',')
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAMIID.Unavailable) when calling the ModifyImageAttribute operation: The AMI ID 'ami-0aef1f7c38d24d19c' is currently pending and may not be used for this operation

Ratherthan catching the error an making the user re-submit the request ec2publishimg should wait for the image to become available.

**Comment by KeithMnemonic** [comment]
Robert,

Do you have steps where I can get an image to go to pending?  So far I am not able to see how to reproduce this issue.

Keith

**Comment by rjschwei** [comment]
@KeithMnemonic just do a copy-image form one region to another

**Comment by KeithMnemonic** [comment]
ok i have it reproduced with 

ec2publishimg -a AWS-RD --image-id ami-0f75e36cc0b92bba1 -r us-east-1 --share-with all

while an image in pending. Thanks for the tip.
