### ISSUE TITLE
ec2uploadimg fails when the helper instance is m5d.xlarge

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/ec2imgutils#46]
invalid literal for int() with base 10: '139.7'

**Comment by Bischoff** [comment]
Apparently, this value is the size of the additional hard disk of `m5d.xlarge`:
```
ip-172-17-17-158:/var/log/rhn/reposync # fdisk -l /dev/nvme1n1
Disk /dev/nvme1n1: 139.7 GiB, 150000000000 bytes, 292968750 sectors
                   ^^^^^^^^^
```

`t2.micro` has no additional hard disk, and therefore does not trigger this issue.
