### ISSUE TITLE
Deprecate image without replacement

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/ec2imgutils#81]
An image may be deprecated without a replacement. This is not currently possible as replacement image is a required argument. Replacement image should instead be an optional argument.

**Comment by rjschwei** [comment]
Yes, we do have images that have no successor. @apozsuse some more low hanging fruit to get you started.

**Comment by apozsuse** [comment]
Hi,
I'll address this issue now, 
I might seize the opportunity to refactor the ec2deprecateimg script a bit (include some functions there and a main() to improve testability) wdyt?

**Comment by smarlowucf** [comment]
> Hi, I'll address this issue now, I might seize the opportunity to refactor the ec2deprecateimg script a bit (include some functions there and a main() to improve testability) wdyt?

Sounds good. There is a known issue with how the package uses scripts instead of entry_points in the python setup that causes trouble for testing the rpm build. This is why the tests are not run in the spec file. Guess I never created a Github issue but it would be nice to see that fixed :+1: .

**Comment by apozsuse** [comment]
Made the PR for the change about the replacement image params not being mandatory.
In case you do NOT include any replacement image and use the '--force' option, the script deletes the existing tag in the image.

I included some refactor in the script to put the functionality in functions and some tests.

I'll try to investigate the setup.py issue now...
